import { useEffect, useState } from "react";
import type { FormEvent } from "react";

import { claimReaderPairingCode, fetchReaderContext } from "../api/publicApi";
import PlatformLogo from "../components/PlatformLogo";
import PublicReader from "./PublicReader";
import {
  clearStoredReaderSession,
  getOrCreateReaderDeviceId,
  getStoredReaderSession,
  setStoredReaderSession,
} from "../utils/readerSession";
import type { ReaderSession } from "../utils/readerSession";

function ChildReaderPortal() {
  const [initialStoredSession] = useState<ReaderSession | null>(() => getStoredReaderSession());
  const [readerSession, setReaderSession] = useState<ReaderSession | null>(initialStoredSession);
  const [sessionChecking, setSessionChecking] = useState(Boolean(initialStoredSession));
  const [sessionChecked, setSessionChecked] = useState(!initialStoredSession);
  const [pairingCode, setPairingCode] = useState("");
  const [deviceName, setDeviceName] = useState("Kid's Device");
  const [pairingLoading, setPairingLoading] = useState(false);
  const [pairingError, setPairingError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    const verifyStoredSession = async () => {
      const storedSession = getStoredReaderSession();
      if (!storedSession) {
        if (!cancelled) {
          setReaderSession(null);
          setSessionChecked(true);
        }
        return;
      }

      setSessionChecking(true);
      try {
        const context = await fetchReaderContext(storedSession.deviceId);
        if (!cancelled) {
          if (context.paired) {
            setReaderSession(storedSession);
          } else {
            clearStoredReaderSession();
            setReaderSession(null);
          }
        }
      } catch {
        if (!cancelled) {
          clearStoredReaderSession();
          setReaderSession(null);
        }
      } finally {
        if (!cancelled) {
          setSessionChecking(false);
          setSessionChecked(true);
        }
      }
    };

    void verifyStoredSession();

    return () => {
      cancelled = true;
    };
  }, []);

  const handleResetSession = () => {
    clearStoredReaderSession();
    setReaderSession(null);
    setPairingCode("");
    setPairingError(null);
  };

  const handlePairing = async (event: FormEvent) => {
    event.preventDefault();
    setPairingLoading(true);
    setPairingError(null);

    try {
      const normalizedCode = pairingCode.trim();
      const deviceId = readerSession?.deviceId ?? getOrCreateReaderDeviceId();
      const paired = await claimReaderPairingCode(normalizedCode, deviceId, deviceName);

      const nextSession: ReaderSession = {
        deviceId,
        childProfileId: paired.childProfile.id,
        childName: paired.childProfile.name,
      };

      setStoredReaderSession(nextSession);
      setReaderSession(nextSession);
      setPairingCode("");
    } catch (error) {
      setPairingError(error instanceof Error ? error.message : "Could not pair this device.");
    } finally {
      setPairingLoading(false);
    }
  };

  if (sessionChecking && !sessionChecked) {
    return (
      <main className="reader-access-shell">
        <div className="state-card">Checking reader session...</div>
      </main>
    );
  }

  if (!readerSession) {
    return (
      <main className="reader-access-shell child-auth-shell">
        <section className="child-auth-layout">
          <article className="auth-card child-auth-card">
            <div className="child-auth-content">
              <h2>Child Reader Access</h2>
              <p>Reader access is private. Enter the 4-digit code generated by the parent account.</p>

              <form className="auth-form child-auth-form" onSubmit={handlePairing}>
                <label>
                  <span>4-Digit Pairing Code</span>
                  <input
                    type="text"
                    value={pairingCode}
                    onChange={(event) => setPairingCode(event.target.value.replace(/\D/g, "").slice(0, 4))}
                    minLength={4}
                    maxLength={4}
                    inputMode="numeric"
                    pattern="\d{4}"
                    required
                  />
                </label>
                <label>
                  <span>Device Name (optional)</span>
                  <input
                    type="text"
                    value={deviceName}
                    onChange={(event) => setDeviceName(event.target.value)}
                    maxLength={120}
                  />
                </label>

                <button type="submit" className="read-button child-auth-submit" disabled={pairingLoading}>
                  {pairingLoading ? "Pairing..." : "Pair Device"}
                </button>
              </form>

              {pairingError && <p className="error-text">{pairingError}</p>}
            </div>
          </article>

          <aside className="child-auth-brand">
            <div>
              <PlatformLogo className="child-brand-logo" />
              <p className="hero-label">HKids Reader</p>
              <h3>Start Reading</h3>
              <p>Ask your parent for the 4-digit code, pair your device, and unlock your story world.</p>
            </div>
          </aside>
        </section>
      </main>
    );
  }

  return <PublicReader readerSession={readerSession} onResetSession={handleResetSession} />;
}

export default ChildReaderPortal;
